#######################
### evaluation mode ###
#######################
eval_mode = false
testset_path = ''

#################
### I\O setup ###
#################
output_dir = "data/runs"

#######################
### landscape setup ###
#######################
landscape_names = ["gb1:with_imputed"]
starts = "starts"

####################
### method setup ###
####################
### explorer ###
explorer_names = ["bo_evo"]
# "random", "adalead", "mcmc", "bo_evo", "bo_enu"

bo_util_funcs = ["UCB"]
bo_uf_params = [0.2]

### batch size ###
expmt_queries_per_round = [384]
model_queries_per_round = [3072]

### input encoding strategy ###
encodings = ["esm-1v"]

### fitness model ###
model_names = ["gpr"]
gp_kernels = ["RBF"]
warm_start = ["warm"]

########################
### simulation setup ###
########################
verbose = false
seeds = [1, 12, 123, 1234, 12345]
rounds = [5]
