#######################
### evaluation mode ###
#######################
eval_mode = false
testset_path = ''

#################
### I\O setup ###
#################
output_dir = "data/runs"

#######################
### landscape setup ###
#######################
landscape_names = ["phoq:measured_only"]
starts = "wt_only"

####################
### method setup ###
####################
### explorer ###
explorer_names = ["bo_evo"]
bo_util_funcs = ["UCB"]
bo_uf_params = [0.2]

### batch size ###
expmt_queries_per_round = [384]
model_queries_per_round = [3072]

### input encoding strategy ###
encodings = ["onehot"]

### fitness model ###
model_names = ["gpr"]
gp_kernels = ["RBF"]
warm_start = ["warm"]

########################
### simulation setup ###
########################
verbose = false
seeds = [1, 12, 123, 1234, 12345]
rounds = [10]
